export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAIL = "GET_ALL_MOVIES_FAIL";

export const GET_RANDOM_MOVIES_REQUEST = "GET_RANDOM_MOVIES_REQUEST";
export const GET_RANDOM_MOVIES_SUCCESS = "GET_RANDOM_MOVIES_SUCCESS";
export const GET_RANDOM_MOVIES_FAIL = "GET_RANDOM_MOVIES_FAIL"

export const GET_MOVIE_BY_ID_REQUEST = "GET_MOVIE_BY_ID_REQUEST";
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS";
export const GET_MOVIE_BY_ID_FAIL = "GET_MOVIE_BY_ID_FAIL"

export const GET_TOP_RATED_MOVIES_REQUEST = "GET_TOP_RATED_MOVIES_REQUEST";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_FAIL = "GET_TOP_RATED_MOVIES_FAIL"