export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAIL = "GET_ALL_MOVIES_FAIL";

export const GET_RANDOM_MOVIES_REQUEST = "GET_RANDOM_MOVIES_REQUEST";
export const GET_RANDOM_MOVIES_SUCCESS = "GET_RANDOM_MOVIES_SUCCESS";
export const GET_RANDOM_MOVIES_FAIL = "GET_RANDOM_MOVIES_FAIL"

export const GET_MOVIE_BY_ID_REQUEST = "GET_MOVIE_BY_ID_REQUEST";
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS";
export const GET_MOVIE_BY_ID_FAIL = "GET_MOVIE_BY_ID_FAIL"

export const GET_TOP_RATED_MOVIES_REQUEST = "GET_TOP_RATED_MOVIES_REQUEST";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_FAIL = "GET_TOP_RATED_MOVIES_FAIL"

export const REVIEW_MOVIE_REQUEST = "REVIEW_MOVIE_REQUEST";
export const REVIEW_MOVIE_SUCCESS = "REVIEW_MOVIE_SUCCESS";
export const REVIEW_MOVIE_FAIL = "REVIEW_MOVIE_FAIL"
export const REVIEW_MOVIE_RESET = "REVIEW_MOVIE_RESET"

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL"

export const DELETE_ALL_MOVIES_REQUEST = "DELETE_ALL_MOVIES_REQUEST";
export const DELETE_ALL_MOVIES_SUCCESS = "DELETE_ALL_MOVIES_SUCCESS";
export const DELETE_ALL_MOVIES_FAIL = "DELETE_ALL_MOVIES_FAIL"
