export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_DELETE_PROFILE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_PROFILE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_PROFILE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_PROFILE_RESET = "USER_DELETE_RESET";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";
export const USER_CHANGE_PASSWORD_RESET = "USER_CHANGE_PASSWORD_RESET";

export const GET_BOOKMARKS_REQUEST = "GET_BOOKMARKS_REQUEST";
export const GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS";
export const GET_BOOKMARKS_FAIL = "GET_BOOKMARKS_FAIL";
export const GET_BOOKMARKS_RESET = "GET_BOOKMARKS_RESET";

export const DELETE_BOOKMARKS_REQUEST = "DELETE_BOOKMARKS_REQUEST";
export const DELETE_BOOKMARKS_SUCCESS = "DELETE_BOOKMARKS_SUCCESS";
export const DELETE_BOOKMARKS_FAIL = "DELETE_BOOKMARKS_FAIL";
export const DELETE_BOOKMARKS_RESET = "DELETE_BOOKMARKS_RESET";

